## Rethinking the data
Now that I have data extracted I wanted to actually organize these spreadsheets into different schemas. This should be advantageous to keep track of the following: Team performance(season wise), Player performance(season wise), game stats of both teams.

### Player schema

| Player        | Pts        | Ast        | Reb        | MIN        | 2M-2A             | 3M-3A             | FG%        | 1M-1A             | 1%         | Or         | Dr         | To         | Stl        | Blk        | Fo         | +/-        | Eff        | Team          |
| ------------- | ---------- | ---------- | ---------- | ---------- | ----------------- | ----------------- | ---------- | ----------------- | ---------- | ---------- | ---------- | ---------- | ---------- | ---------- | ---------- | ---------- | ---------- | ------------- |
| dtype: String | dtype: int | dtype: int | dtype: int | dtype: int | dtype: object: int | dtype: object: int | dtype: int | dtype: object: int | dtype: int | dtype: int | dtype: int | dtype: int | dtype: int | dtype: int | dtype: int | dtype: int | dtype: int | dtype: String |
|               |            |            |            |            |                   |                   |            |                   |            |            |            |            |            |            |            |            |            |               |


### Team schema

| Team          | Pts        | Ast        | Reb        | MIN        | 2M-2A              | 3M-3A              | FG%          | 1M-1A         | 1%           | Or         | Dr         | To         | Stl        | Blk        | Fo         | +/-        | Eff        | PLayers               |
| ------------- | ---------- | ---------- | ---------- | ---------- | ------------------ | ------------------ | ------------ | ------------- | ------------ | ---------- | ---------- | ---------- | ---------- | ---------- | ---------- | ---------- | ---------- | --------------------- |
| dtype: String | dtype: int | dtype: int | dtype: int | dtype: int | dtype: object: int | dtype: object: int | dtype: float | dtype: object | dtype: float | dtype: int | dtype: int | dtype: int | dtype: int | dtype: int | dtype: int | dtype: int | dtype: int | dtype: Object: String |
|               |            |            |            |            |                    |                    |              |               |              |            |            |            |            |            |            |            |            |                       |

### Game schema

| Teams          | Pts         | Ast         | Reb         | MIN         | 2M-2A       | 3M-3A       | FG%           | 1M-1A       | 1%            | Or          | Dr          | To          | Stl | Blk | Fo  | +/- | Eff | PLayers |
| -------------- | ----------- | ----------- | ----------- | ----------- | ----------- | ----------- | ------------- | ----------- | ------------- | ----------- | ----------- | ----------- | --- | --- | --- | --- | --- | ------- |
| object: String | object: int | object: int | object: int | object: int | object: int | object: int | object: float | object: int | object: float | object: int | object: int | object: int |     |     |     |     |     |         |

So let's get to implementing these schemas and seeing if these new datasets can be of more use.

In [77]:
import pandas as pd
import numpy as np

original_df = pd.read_csv('../1_Data_Collection/datasets/atlanta-hawks-cleveland-cavaliers-2024-01-21.csv')
second_atlanta_df = pd.read_csv('../1_Data_Collection/datasets/atlanta-hawks-detroit-pistons-2023-12-19.csv')
second_cleveland_df = pd.read_csv('../1_Data_Collection/datasets/cleveland-cavaliers-new-orleans-pelicans-2023-12-22.csv')

In [78]:
# Implement player schema
player_df_atl_clv = original_df.copy()
# Remove all rows where player has the same value as the team
player_df_atl_clv = player_df_atl_clv[player_df_atl_clv['PLAYER'] != player_df_atl_clv['Team']]
player_df_atl_clv

,PLAYER,Pts,Reb,Ast,MIN,2M-2A,3M-3A,FG%,1M-1A,1%,Or,Dr,To,Stl,Blk,Fo,+/-,Eff,Team
0,DejounteMurray,24,9,5,35,8-12,2-7,52.6%,2-2,100.0%,0,9,2,1,0,2,-20,28,AtlantaHawks
1,JalenT.Johnson,20,7,4,34,7-11,1-5,50.0%,3-6,50.0%,1,6,1,1,2,2,-19,22,AtlantaHawks
2,TraeYoung,15,1,5,28,3-8,3-4,50.0%,0-0,-,0,1,4,0,0,2,-20,11,AtlantaHawks
3,BogdanBogdanovic,14,2,4,28,4-5,1-6,45.5%,3-4,75.0%,0,2,1,1,0,0,-13,13,AtlantaHawks
4,ClintCapela,6,9,0,22,3-8,0-0,37.5%,0-0,-,5,4,2,1,2,2,-14,11,AtlantaHawks
5,PattyMills,6,0,0,10,0-0,2-3,66.7%,0-0,-,0,0,0,1,0,1,3,6,AtlantaHawks
6,GarrisonMathews,4,2,2,14,0-0,1-3,33.3%,1-1,100.0%,0,2,0,0,0,0,-3,6,AtlantaHawks
7,SethLundy,3,0,0,3,0-0,1-2,50.0%,0-0,-,0,0,0,0,0,0,3,2,AtlantaHawks
8,AJGriffin,2,0,0,3,1-1,0-1,50.0%,0-0,-,0,0,0,0,0,0,3,1,AtlantaHawks
9,OnyekaOkongwu,1,6,2,23,0-3,0-0,0.0%,1-2,50.0%,2,4,0,0,0,3,-10,5,AtlantaHawks
10,BrunoFernando,0,1,1,3,0-0,0-1,0.0%,0-0,-,0,1,0,0,0,0,3,1,AtlantaHawks
11,TrentForrest,0,1,0,6,0-1,0-0,0.0%,0-0,-,0,1,0,0,0,0,6,0,AtlantaHawks
12,SaddiqBey,0,7,2,30,0-6,0-6,0.0%,0-0,-,3,4,1,0,0,3,-24,-4,AtlantaHawks
14,DonovanMitchell,18,6,8,36,6-11,0-6,35.3%,6-6,100.0%,0,6,1,0,1,3,17,21,ClevelandCavaliers
15,SamMerrill,18,4,6,30,1-2,5-14,37.5%,1-1,100.0%,0,4,1,0,0,2,8,17,ClevelandCavaliers
16,DeanWade,17,5,0,26,1-1,5-6,85.7%,0-0,-,1,4,0,1,0,1,11,22,ClevelandCavaliers
17,JarrettAllen,14,11,2,33,6-8,0-0,75.0%,2-2,100.0%,1,10,4,3,3,2,7,27,ClevelandCavaliers
18,GeorgesNiang,14,5,2,21,1-1,4-8,55.6%,0-0,-,0,5,0,0,1,2,11,18,ClevelandCavaliers
19,MaxStrus,13,3,7,20,4-6,1-4,50.0%,2-2,100.0%,2,1,2,1,0,1,15,17,ClevelandCavaliers
20,IsaacOkoro,12,5,2,33,4-6,1-3,55.6%,1-3,33.3%,0,5,2,2,0,3,19,13,ClevelandCavaliers
21,TristanThompson,6,5,2,14,3-3,0-1,75.0%,0-0,-,0,5,0,0,1,0,14,13,ClevelandCavaliers
22,CraigPorter,4,5,3,21,1-2,0-1,33.3%,2-2,100.0%,0,5,3,0,0,2,5,7,ClevelandCavaliers
23,DamianJones,0,0,0,3,0-0,0-0,-,0-0,-,0,0,0,0,0,0,-1,0,ClevelandCavaliers
24,PeteNance,0,0,0,3,0-2,0-0,0.0%,0-0,-,0,0,0,0,0,0,-1,-2,ClevelandCavaliers

Above we've removed all rows that indicate team stats. Those stats will later be stored into a seperate dataframe.

In [79]:
# Implement player schema for second game of both teams
player_df_atl = second_atlanta_df.copy()
player_df_clv = second_cleveland_df.copy()

# Remove all rows where player has the same value as the team
player_df_atl = player_df_atl[player_df_atl['PLAYER'] != player_df_atl['Team']]
player_df_clv = player_df_clv[player_df_clv['PLAYER'] != player_df_clv['Team']]
player_df_atl

,PLAYER,Pts,Reb,Ast,MIN,2M-2A,3M-3A,FG%,1M-1A,1%,Or,Dr,To,Stl,Blk,Fo,+/-,Eff,Team
0,TraeYoung,31,4,15,38,4-6,4-11,47.1%,11-12,91.7%,0,4,5,0,0,3,16,35,AtlantaHawks
1,SaddiqBey,21,4,1,42,6-8,2-7,53.3%,3-5,60.0%,2,2,1,2,0,1,9,18,AtlantaHawks
2,DejounteMurray,20,3,3,33,5-8,3-5,61.5%,1-2,50.0%,0,3,1,1,1,2,2,21,AtlantaHawks
3,De&#039;AndreHunter,19,6,2,29,2-9,5-6,46.7%,0-0,-,1,5,4,1,2,5,9,18,AtlantaHawks
4,ClintCapela,17,15,2,28,7-11,0-0,63.6%,3-3,100.0%,7,8,1,1,3,3,10,33,AtlantaHawks
5,OnyekaOkongwu,14,2,1,23,5-6,0-0,83.3%,4-4,100.0%,0,2,2,0,1,2,0,15,AtlantaHawks
6,GarrisonMathews,6,3,0,23,0-0,2-5,40.0%,0-1,0.0%,1,2,2,0,2,5,-8,5,AtlantaHawks
7,WesleyMatthews,2,2,1,15,1-1,0-1,50.0%,0-0,-,0,2,1,1,1,1,-9,5,AtlantaHawks
8,SethLundy,0,1,0,9,0-0,0-1,0.0%,0-0,-,0,1,0,0,0,2,1,0,AtlantaHawks
10,CadeCunningham,43,5,7,44,13-19,3-5,66.7%,8-9,88.9%,1,4,3,3,1,1,-2,47,DetroitPistons
11,BojanBogdanovic,25,2,2,39,4-8,5-9,52.9%,2-3,66.7%,1,1,2,0,0,3,4,18,DetroitPistons
12,MarvinBagley,17,1,0,23,7-12,0-0,58.3%,3-4,75.0%,1,0,2,0,0,2,-10,10,DetroitPistons
13,JadenIvey,15,8,4,29,6-11,0-2,46.2%,3-5,60.0%,2,6,2,0,0,6,-12,16,DetroitPistons
14,JamesWiseman,10,7,2,25,5-5,0-0,100.0%,0-2,0.0%,2,5,2,0,0,2,4,15,DetroitPistons
15,AlecBurks,6,2,2,23,2-9,0-2,18.2%,2-2,100.0%,1,1,0,1,0,3,-5,2,DetroitPistons
16,MarcusSasser,5,1,1,21,1-2,1-1,66.7%,0-0,-,0,1,0,1,1,6,10,8,DetroitPistons
17,AusarThompson,2,8,3,19,1-4,0-1,20.0%,0-0,-,3,5,2,1,0,2,-16,8,DetroitPistons
18,JoeHarris,1,2,2,12,0-0,0-1,0.0%,1-2,50.0%,1,1,0,1,1,1,1,5,DetroitPistons
19,IsaiahLivers,0,0,0,4,0-2,0-1,0.0%,0-0,-,0,0,0,0,0,0,-4,-3,DetroitPistons

In [80]:
player_df_clv

,PLAYER,Pts,Reb,Ast,MIN,2M-2A,3M-3A,FG%,1M-1A,1%,Or,Dr,To,Stl,Blk,Fo,+/-,Eff,Team
0,DeanWade,20,9,0,26,1-3,6-8,63.6%,0-0,-,0,9,0,0,2,3,-4,27,ClevelandCavaliers
1,IsaacOkoro,16,3,4,32,5-5,2-5,70.0%,0-1,0.0%,1,2,0,1,0,2,-19,20,ClevelandCavaliers
2,JarrettAllen,14,7,3,27,7-8,0-0,87.5%,0-0,-,1,6,1,1,0,0,-6,23,ClevelandCavaliers
3,MaxStrus,13,3,5,33,2-4,2-12,25.0%,3-5,60.0%,0,3,3,0,0,2,-15,4,ClevelandCavaliers
4,GeorgesNiang,11,2,1,19,1-1,3-7,50.0%,0-0,-,0,2,3,0,1,1,-13,8,ClevelandCavaliers
5,CarisLeVert,9,0,4,23,2-5,1-4,33.3%,2-2,100.0%,0,0,1,1,0,1,-24,7,ClevelandCavaliers
6,CraigPorter,7,3,11,29,2-8,1-1,33.3%,0-0,-,0,3,2,1,0,1,3,14,ClevelandCavaliers
7,TristanThompson,6,7,3,21,3-5,0-0,60.0%,0-0,-,4,3,0,0,0,2,-13,14,ClevelandCavaliers
8,IsaiahMobley,3,0,1,4,0-0,1-1,100.0%,0-0,-,0,0,0,0,0,0,2,4,ClevelandCavaliers
9,EmoniBates,3,0,1,9,0-2,1-3,20.0%,0-0,-,0,0,0,0,0,1,-9,0,ClevelandCavaliers
10,DamianJones,2,1,0,4,1-1,0-0,100.0%,0-0,-,0,1,0,0,0,0,2,3,ClevelandCavaliers
11,SamMerrill,0,0,1,12,0-1,0-3,0.0%,0-0,-,0,0,1,0,0,0,1,-4,ClevelandCavaliers
13,TreyMurphyIII,28,4,3,28,4-6,6-10,62.5%,2-2,100.0%,0,4,1,1,1,1,20,30,NewOrleansPelicans
14,C.J.McCollum,18,6,4,34,5-7,2-8,46.7%,2-2,100.0%,0,6,2,4,1,2,13,23,NewOrleansPelicans
15,BrandonIngram,17,7,6,28,5-9,1-3,50.0%,4-4,100.0%,1,6,3,0,0,2,12,21,NewOrleansPelicans
16,NajiMarshall,14,6,3,22,3-7,1-4,36.4%,5-7,71.4%,3,3,1,1,0,1,16,14,NewOrleansPelicans
17,JonasValanciunas,13,7,5,28,5-6,1-3,66.7%,0-0,-,1,6,2,1,1,3,-3,22,NewOrleansPelicans
18,JeremiahRobinson-Earl,11,5,1,20,4-4,1-2,83.3%,0-0,-,0,5,0,0,0,1,22,16,NewOrleansPelicans
19,DysonDaniels,7,2,1,20,2-3,1-1,75.0%,0-0,-,0,2,0,0,0,1,-2,9,NewOrleansPelicans
20,HerbertJones,7,1,4,30,3-6,0-1,42.9%,1-1,100.0%,1,0,0,0,1,1,5,9,NewOrleansPelicans
21,JordanHawkins,6,0,2,12,0-2,2-3,40.0%,0-0,-,0,0,0,0,0,1,-4,5,NewOrleansPelicans
22,JoseAlvarado,2,2,3,18,1-1,0-0,100.0%,0-0,-,1,1,0,0,0,2,16,7,NewOrleansPelicans

Now we have at least two datasets for the ATL Hawks and the Cleveland Cavs.

Let's run iterations over these data frames to convert their values

In [81]:
# Iterate through cleveland dataframe and convert all string values to int or float
for index, row in player_df_clv.iterrows():
    player_df_clv.at[index, '2M-2A'] = np.array(player_df_clv.at[index, '2M-2A'].split('-'), dtype=int)
    player_df_clv.at[index, '3M-3A'] = np.array(player_df_clv.at[index, '3M-3A'].split('-'), dtype=int)
    player_df_clv.at[index, '1M-1A'] = np.array(player_df_clv.at[index, '1M-1A'].split('-'), dtype=int)
    try:
        player_df_clv.at[index, 'FG%'] = float(player_df_clv.at[index, 'FG%'].rstrip('%'))
    except:
        player_df_clv.at[index, 'FG%'] = 0
    try:
        player_df_clv.at[index, '1%'] = float(player_df_clv.at[index, '1%'].rstrip('%'))
    except:
        player_df_clv.at[index, '1%'] = 0

player_df_clv

,PLAYER,Pts,Reb,Ast,MIN,2M-2A,3M-3A,FG%,1M-1A,1%,Or,Dr,To,Stl,Blk,Fo,+/-,Eff,Team
0,DeanWade,20,9,0,26,"[1, 3]","[6, 8]",63.6,"[0, 0]",0,0,9,0,0,2,3,-4,27,ClevelandCavaliers
1,IsaacOkoro,16,3,4,32,"[5, 5]","[2, 5]",70.0,"[0, 1]",0.0,1,2,0,1,0,2,-19,20,ClevelandCavaliers
2,JarrettAllen,14,7,3,27,"[7, 8]","[0, 0]",87.5,"[0, 0]",0,1,6,1,1,0,0,-6,23,ClevelandCavaliers
3,MaxStrus,13,3,5,33,"[2, 4]","[2, 12]",25.0,"[3, 5]",60.0,0,3,3,0,0,2,-15,4,ClevelandCavaliers
4,GeorgesNiang,11,2,1,19,"[1, 1]","[3, 7]",50.0,"[0, 0]",0,0,2,3,0,1,1,-13,8,ClevelandCavaliers
5,CarisLeVert,9,0,4,23,"[2, 5]","[1, 4]",33.3,"[2, 2]",100.0,0,0,1,1,0,1,-24,7,ClevelandCavaliers
6,CraigPorter,7,3,11,29,"[2, 8]","[1, 1]",33.3,"[0, 0]",0,0,3,2,1,0,1,3,14,ClevelandCavaliers
7,TristanThompson,6,7,3,21,"[3, 5]","[0, 0]",60.0,"[0, 0]",0,4,3,0,0,0,2,-13,14,ClevelandCavaliers
8,IsaiahMobley,3,0,1,4,"[0, 0]","[1, 1]",100.0,"[0, 0]",0,0,0,0,0,0,0,2,4,ClevelandCavaliers
9,EmoniBates,3,0,1,9,"[0, 2]","[1, 3]",20.0,"[0, 0]",0,0,0,0,0,0,1,-9,0,ClevelandCavaliers
10,DamianJones,2,1,0,4,"[1, 1]","[0, 0]",100.0,"[0, 0]",0,0,1,0,0,0,0,2,3,ClevelandCavaliers
11,SamMerrill,0,0,1,12,"[0, 1]","[0, 3]",0.0,"[0, 0]",0,0,0,1,0,0,0,1,-4,ClevelandCavaliers
13,TreyMurphyIII,28,4,3,28,"[4, 6]","[6, 10]",62.5,"[2, 2]",100.0,0,4,1,1,1,1,20,30,NewOrleansPelicans
14,C.J.McCollum,18,6,4,34,"[5, 7]","[2, 8]",46.7,"[2, 2]",100.0,0,6,2,4,1,2,13,23,NewOrleansPelicans
15,BrandonIngram,17,7,6,28,"[5, 9]","[1, 3]",50.0,"[4, 4]",100.0,1,6,3,0,0,2,12,21,NewOrleansPelicans
16,NajiMarshall,14,6,3,22,"[3, 7]","[1, 4]",36.4,"[5, 7]",71.4,3,3,1,1,0,1,16,14,NewOrleansPelicans
17,JonasValanciunas,13,7,5,28,"[5, 6]","[1, 3]",66.7,"[0, 0]",0,1,6,2,1,1,3,-3,22,NewOrleansPelicans
18,JeremiahRobinson-Earl,11,5,1,20,"[4, 4]","[1, 2]",83.3,"[0, 0]",0,0,5,0,0,0,1,22,16,NewOrleansPelicans
19,DysonDaniels,7,2,1,20,"[2, 3]","[1, 1]",75.0,"[0, 0]",0,0,2,0,0,0,1,-2,9,NewOrleansPelicans
20,HerbertJones,7,1,4,30,"[3, 6]","[0, 1]",42.9,"[1, 1]",100.0,1,0,0,0,1,1,5,9,NewOrleansPelicans
21,JordanHawkins,6,0,2,12,"[0, 2]","[2, 3]",40.0,"[0, 0]",0,0,0,0,0,0,1,-4,5,NewOrleansPelicans
22,JoseAlvarado,2,2,3,18,"[1, 1]","[0, 0]",100.0,"[0, 0]",0,1,1,0,0,0,2,16,7,NewOrleansPelicans

In [82]:
# Iterate through Atlanta dataframe and convert all string values to int or float
for index, row in player_df_atl.iterrows():
    player_df_atl.at[index, '2M-2A'] = np.array(player_df_atl.at[index, '2M-2A'].split('-'), dtype=int)
    player_df_atl.at[index, '3M-3A'] = np.array(player_df_atl.at[index, '3M-3A'].split('-'), dtype=int)
    player_df_atl.at[index, '1M-1A'] = np.array(player_df_atl.at[index, '1M-1A'].split('-'), dtype=int)
    try:
        player_df_atl.at[index, 'FG%'] = float(player_df_atl.at[index, 'FG%'].rstrip('%'))
    except:
        player_df_atl.at[index, 'FG%'] = 0
    try:
        player_df_atl.at[index, '1%'] = float(player_df_atl.at[index, '1%'].rstrip('%'))
    except:
        player_df_atl.at[index, '1%'] = 0

player_df_atl

,PLAYER,Pts,Reb,Ast,MIN,2M-2A,3M-3A,FG%,1M-1A,1%,Or,Dr,To,Stl,Blk,Fo,+/-,Eff,Team
0,TraeYoung,31,4,15,38,"[4, 6]","[4, 11]",47.1,"[11, 12]",91.7,0,4,5,0,0,3,16,35,AtlantaHawks
1,SaddiqBey,21,4,1,42,"[6, 8]","[2, 7]",53.3,"[3, 5]",60.0,2,2,1,2,0,1,9,18,AtlantaHawks
2,DejounteMurray,20,3,3,33,"[5, 8]","[3, 5]",61.5,"[1, 2]",50.0,0,3,1,1,1,2,2,21,AtlantaHawks
3,De&#039;AndreHunter,19,6,2,29,"[2, 9]","[5, 6]",46.7,"[0, 0]",0,1,5,4,1,2,5,9,18,AtlantaHawks
4,ClintCapela,17,15,2,28,"[7, 11]","[0, 0]",63.6,"[3, 3]",100.0,7,8,1,1,3,3,10,33,AtlantaHawks
5,OnyekaOkongwu,14,2,1,23,"[5, 6]","[0, 0]",83.3,"[4, 4]",100.0,0,2,2,0,1,2,0,15,AtlantaHawks
6,GarrisonMathews,6,3,0,23,"[0, 0]","[2, 5]",40.0,"[0, 1]",0.0,1,2,2,0,2,5,-8,5,AtlantaHawks
7,WesleyMatthews,2,2,1,15,"[1, 1]","[0, 1]",50.0,"[0, 0]",0,0,2,1,1,1,1,-9,5,AtlantaHawks
8,SethLundy,0,1,0,9,"[0, 0]","[0, 1]",0.0,"[0, 0]",0,0,1,0,0,0,2,1,0,AtlantaHawks
10,CadeCunningham,43,5,7,44,"[13, 19]","[3, 5]",66.7,"[8, 9]",88.9,1,4,3,3,1,1,-2,47,DetroitPistons
11,BojanBogdanovic,25,2,2,39,"[4, 8]","[5, 9]",52.9,"[2, 3]",66.7,1,1,2,0,0,3,4,18,DetroitPistons
12,MarvinBagley,17,1,0,23,"[7, 12]","[0, 0]",58.3,"[3, 4]",75.0,1,0,2,0,0,2,-10,10,DetroitPistons
13,JadenIvey,15,8,4,29,"[6, 11]","[0, 2]",46.2,"[3, 5]",60.0,2,6,2,0,0,6,-12,16,DetroitPistons
14,JamesWiseman,10,7,2,25,"[5, 5]","[0, 0]",100.0,"[0, 2]",0.0,2,5,2,0,0,2,4,15,DetroitPistons
15,AlecBurks,6,2,2,23,"[2, 9]","[0, 2]",18.2,"[2, 2]",100.0,1,1,0,1,0,3,-5,2,DetroitPistons
16,MarcusSasser,5,1,1,21,"[1, 2]","[1, 1]",66.7,"[0, 0]",0,0,1,0,1,1,6,10,8,DetroitPistons
17,AusarThompson,2,8,3,19,"[1, 4]","[0, 1]",20.0,"[0, 0]",0,3,5,2,1,0,2,-16,8,DetroitPistons
18,JoeHarris,1,2,2,12,"[0, 0]","[0, 1]",0.0,"[1, 2]",50.0,1,1,0,1,1,1,1,5,DetroitPistons
19,IsaiahLivers,0,0,0,4,"[0, 2]","[0, 1]",0.0,"[0, 0]",0,0,0,0,0,0,0,-4,-3,DetroitPistons

In [83]:
# Iterate through cleveland and atlanta dataframe and convert all string values to int or float

for index, row in player_df_atl_clv.iterrows():
    player_df_atl_clv.at[index, '2M-2A'] = np.array(player_df_atl_clv.at[index, '2M-2A'].split('-'), dtype=int)
    player_df_atl_clv.at[index, '3M-3A'] = np.array(player_df_atl_clv.at[index, '3M-3A'].split('-'), dtype=int)
    player_df_atl_clv.at[index, '1M-1A'] = np.array(player_df_atl_clv.at[index, '1M-1A'].split('-'), dtype=int)
    try:
        player_df_atl_clv.at[index, 'FG%'] = float(player_df_atl_clv.at[index, 'FG%'].rstrip('%'))
    except:
        player_df_atl_clv.at[index, 'FG%'] = 0
    try:
        player_df_atl_clv.at[index, '1%'] = float(player_df_atl_clv.at[index, '1%'].rstrip('%'))
    except:
        player_df_atl_clv.at[index, '1%'] = 0
        
player_df_atl_clv

,PLAYER,Pts,Reb,Ast,MIN,2M-2A,3M-3A,FG%,1M-1A,1%,Or,Dr,To,Stl,Blk,Fo,+/-,Eff,Team
0,DejounteMurray,24,9,5,35,"[8, 12]","[2, 7]",52.6,"[2, 2]",100.0,0,9,2,1,0,2,-20,28,AtlantaHawks
1,JalenT.Johnson,20,7,4,34,"[7, 11]","[1, 5]",50.0,"[3, 6]",50.0,1,6,1,1,2,2,-19,22,AtlantaHawks
2,TraeYoung,15,1,5,28,"[3, 8]","[3, 4]",50.0,"[0, 0]",0,0,1,4,0,0,2,-20,11,AtlantaHawks
3,BogdanBogdanovic,14,2,4,28,"[4, 5]","[1, 6]",45.5,"[3, 4]",75.0,0,2,1,1,0,0,-13,13,AtlantaHawks
4,ClintCapela,6,9,0,22,"[3, 8]","[0, 0]",37.5,"[0, 0]",0,5,4,2,1,2,2,-14,11,AtlantaHawks
5,PattyMills,6,0,0,10,"[0, 0]","[2, 3]",66.7,"[0, 0]",0,0,0,0,1,0,1,3,6,AtlantaHawks
6,GarrisonMathews,4,2,2,14,"[0, 0]","[1, 3]",33.3,"[1, 1]",100.0,0,2,0,0,0,0,-3,6,AtlantaHawks
7,SethLundy,3,0,0,3,"[0, 0]","[1, 2]",50.0,"[0, 0]",0,0,0,0,0,0,0,3,2,AtlantaHawks
8,AJGriffin,2,0,0,3,"[1, 1]","[0, 1]",50.0,"[0, 0]",0,0,0,0,0,0,0,3,1,AtlantaHawks
9,OnyekaOkongwu,1,6,2,23,"[0, 3]","[0, 0]",0.0,"[1, 2]",50.0,2,4,0,0,0,3,-10,5,AtlantaHawks
10,BrunoFernando,0,1,1,3,"[0, 0]","[0, 1]",0.0,"[0, 0]",0,0,1,0,0,0,0,3,1,AtlantaHawks
11,TrentForrest,0,1,0,6,"[0, 1]","[0, 0]",0.0,"[0, 0]",0,0,1,0,0,0,0,6,0,AtlantaHawks
12,SaddiqBey,0,7,2,30,"[0, 6]","[0, 6]",0.0,"[0, 0]",0,3,4,1,0,0,3,-24,-4,AtlantaHawks
14,DonovanMitchell,18,6,8,36,"[6, 11]","[0, 6]",35.3,"[6, 6]",100.0,0,6,1,0,1,3,17,21,ClevelandCavaliers
15,SamMerrill,18,4,6,30,"[1, 2]","[5, 14]",37.5,"[1, 1]",100.0,0,4,1,0,0,2,8,17,ClevelandCavaliers
16,DeanWade,17,5,0,26,"[1, 1]","[5, 6]",85.7,"[0, 0]",0,1,4,0,1,0,1,11,22,ClevelandCavaliers
17,JarrettAllen,14,11,2,33,"[6, 8]","[0, 0]",75.0,"[2, 2]",100.0,1,10,4,3,3,2,7,27,ClevelandCavaliers
18,GeorgesNiang,14,5,2,21,"[1, 1]","[4, 8]",55.6,"[0, 0]",0,0,5,0,0,1,2,11,18,ClevelandCavaliers
19,MaxStrus,13,3,7,20,"[4, 6]","[1, 4]",50.0,"[2, 2]",100.0,2,1,2,1,0,1,15,17,ClevelandCavaliers
20,IsaacOkoro,12,5,2,33,"[4, 6]","[1, 3]",55.6,"[1, 3]",33.3,0,5,2,2,0,3,19,13,ClevelandCavaliers
21,TristanThompson,6,5,2,14,"[3, 3]","[0, 1]",75.0,"[0, 0]",0,0,5,0,0,1,0,14,13,ClevelandCavaliers
22,CraigPorter,4,5,3,21,"[1, 2]","[0, 1]",33.3,"[2, 2]",100.0,0,5,3,0,0,2,5,7,ClevelandCavaliers
23,DamianJones,0,0,0,3,"[0, 0]","[0, 0]",0,"[0, 0]",0,0,0,0,0,0,0,-1,0,ClevelandCavaliers
24,PeteNance,0,0,0,3,"[0, 2]","[0, 0]",0.0,"[0, 0]",0,0,0,0,0,0,0,-1,-2,ClevelandCavaliers

## Merging

Now that all of our values that are supposed to be numbers are actually numbers. We can do a quick sum on each row. Since some of them arrays and some of them are strings we might need to iterate over everything again.

In [84]:
def sum_array(arr1, arr2):
    return np.add(arr1, arr2)

In [114]:
list_of_atl_frames = [player_df_atl, player_df_atl_clv]
Atl_players = pd.DataFrame(player_df_atl, columns=player_df_atl.columns, index=None)

for index, row in player_df_atl_clv.iterrows():
    if row['PLAYER'] not in Atl_players['PLAYER'].values:
        Atl_players[index] = row
    else:
        # index = Atl_players[Atl_players['PLAYER'] == row['PLAYER']].index[0]
        Atl_players.at[index, 'Pts'] = Atl_players.at[index, 'Pts'] + row['Pts']
        Atl_players.at[index, 'Ast'] = Atl_players.at[index, 'Ast'] + row['Ast']
        Atl_players.at[index, 'Reb'] = Atl_players.at[index, 'Reb'] + row['Reb']
        Atl_players.at[index, 'MIN'] = Atl_players.at[index, 'MIN'] + row['MIN']
        Atl_players.at[index, '2M-2A'] = sum_array(Atl_players.at[index, '2M-2A'], row['2M-2A'])
        Atl_players.at[index, '3M-3A'] = sum_array(Atl_players.at[index, '3M-3A'], row['3M-3A'])
        Atl_players.at[index, '1M-1A'] = sum_array(Atl_players.at[index, '1M-1A'], row['1M-1A'])
        Atl_players.at[index, '1%'] = (Atl_players.at[index, '1%'] + row['1%']) / 2
        Atl_players.at[index, 'Stl'] = Atl_players.at[index, 'Stl'] + row['Stl']
        Atl_players.at[index, 'Blk'] = Atl_players.at[index, 'Blk'] + row['Blk']
        Atl_players.at[index, 'To'] = Atl_players.at[index, 'To'] + row['To']
        # Atl_players.at[index, 'PF'] = Atl_players.at[index, 'PF'] + row['PF']
        Atl_players.at[index, '+/-'] = Atl_players.at[index, '+/-'] + row['+/-']
        Atl_players.at[index, 'FG%'] = Atl_players.at[index, 'FG%'] + row['FG%']
        Atl_players.at[index, 'Eff'] = Atl_players.at[index, 'Eff'] + row['Eff']
        Atl_players.at[index, 'Fo'] = Atl_players.at[index, 'Fo'] + row['Fo']
            
Atl_players[Atl_players['PLAYER'] == 'TraeYoung']

KeyError: 9